### ISSUE TITLE
Any particular reason openapoc tanks my computer?

### ISSUE THREAD

**Issue by samuelroy21** [pmprog/OpenApoc#112]
Currently running an i5 with 8 gigs of RAM on 64 bit Windows 10, and compiled using the latest version of MSVC++.

**Comment by JonnyH** [comment]
Are you running a 'debug' or 'release' build? The 'debug' mode for MSVC is known to be extremely slow, taking over a minute to load the game, and slow in-game as it iterates over all objects in the city/battlescape to update the state and draw.

'Release' should be fine - it works over 60fps on my 5 year old i3 laptop :)

**Comment by JonnyH** [comment]
Oh, and if you expect to "play" OpenApoc you'll be disappointed, it's still in early development with many core features still not yet implemented.

**Comment by samuelroy21** [comment]
I'm aware, was hoping to do some development. Thanks for the info.

**Comment by JonnyH** [comment]
Possibly of note, the MSVC2017 RC release notes explicitly mention the the std::vector iterator performance in debug mode has been "slightly improved" - so clearly MS are aware of this issue, and 2017 may be slightly better (though I've not tested MSVC2017 myself - I tend to use Linux for most of my dev, and gcc and clang don't seem to have this same issue)

**Comment by samuelroy21** [comment]
Alright. Anything of note that I should know about the project before I dig in?

**Comment by JonnyH** [comment]
I tend to idle in #OpenApoc IRC channel on freenode.net - that's probably the best way of keeping in contact.

We have a 'kinda todo' list at https://trello.com/b/lX5Y3DwR/openapoc - I keep forgetting to update it though, so it's often slightly out of date :)

I have appveyor (For Windows) and Travis-CI (for linux and OSX) continuous integration setup - the config files are in the repostiory, so if you fork it you can sign up for a 'free' account there and enable it on your repository and it 'should' work. My repository's are at https://ci.appveyor.com/project/JonnyH/openapoc and https://travis-ci.org/JonnyH/OpenApoc respectively.

We also have a forum at openapoc.pmprog.co.uk - it might be useful for more 'lasting' communication than IRC.

One thing to be aware of is the build currently expects the cd.iso file from the original apocalypse game (I use the one from steam) under the 'data/' directory - it reads that to extract some data to generate the initial game state, as well as reading the sprite images etc. at runtime.

I've been a bit inactive recently due to some family stuff and the like, so it's been a bit quiet, but we're still continuing work - just slowly :)
