### ISSUE TITLE
Spritesheet error on Windows

### ISSUE THREAD

**Issue by pmprog** [pmprog/OpenApoc#63]
Took ages to start the game, and got this:

    A fatal error has occured

    Spritesheet size 957 would be over max array size 512 - falling back to 'slow' path.

Did actually load and work though

**Comment by JonnyH** [comment]
Let me guess, this is using the Intel graphics driver? This exact thing happened on mine for a while, but I think a driver update fixed it. It's clearly a driver limitation, not a hw limit.

The super slow texture upload I can't do anything about, and the slow-mode-fallback really should be a warning, not an error.

I could try to resurrect my sprite packing branch and see if that helps (using a packed 2d spritesheet instead of a texture array) but that's not high on my prio list ATM.

It might be useful to run an opengl extension & limits viewer and paste the results (I'll probably add the same info to the openapoc log soon ish if crappy drivers are going to be common)

**Comment by pmprog** [comment]
Yep, it was an Intel Graphics driver. No worries about it, just first time I'd seen it. It'll be fine for now
