### ISSUE TITLE
libsmacker updated to r26

### ISSUE THREAD

**Issue by greg-kennedy** [pmprog/OpenApoc#71]
...upstream:
https://sourceforge.net/p/libsmacker/code/26/

This release fixes some palette handling and weird error message printout.  Consider updating : )

**Comment by JonnyH** [comment]
Cheers - updated in d6fe7ff

A quick test shows this fixes the message:

libsmacker::palette_render(s,p,size) - ERROR: overflow, 0x80 attempt to copy 3 bytes from 768 to 765

being printed out in frame 444 of Xcom Apocalypse's 'intro1.smk'. Not checked for any visual differences though.

(BTW - I hope you don't mind me having a mirror on github - it's just easier to integrate as a git submodule instead of trying to fight with svn :)
