### ISSUE TITLE
Textedit doesn't work

### ISSUE THREAD

**Issue by ShadowDancer** [pmprog/OpenApoc#76]
Looks like after moving to SDL api something got broken (onclick event sets editing = true and editing = false in single event. 

Could you take a look @SupSuper ?

**Comment by pmprog** [comment]
I'll hopefully have a look at this tonight... :smile:

**Comment by pmprog** [comment]
Hmmm, I've just tried this on Windows, and seems to work _okay-ish_. 
It's a little slow. It can take about 1sec after clicking the base name for the edit to start. I'll try and look into it a bit deeper though later

**Comment by ShadowDancer** [comment]
Thanks!

**Comment by pmprog** [comment]
I wouldn't close this yet.

However, one thing I have noticed, and maybe @SupSuper could clarify this (I believe he ported the code?), but looking in the "basescreen.cpp" file, when the event handler is, the form ui gets to handle events, however, it's not checking if the event *was* handled before the rest of the event handler runs.

Not sure if this will make a difference in this case, but if the UI actually processes the event, the rest of the EventOccurred function should really be skipped. This is why the "Handled" property of the Event class exists.

What this prevents is if you click on a form UI element, that it both affects the UI form and whatever other code handles mouse click on what's "behind" the form

**Comment by sfalexrog** [comment]
@pmprog, which revision did you test? I've disabled some code in a72c58a9a85c3ae458d0d2132a80e6ad3e253a4e that would make the TextEdit stop processing input events (specifically lines 62-66 in the master branch, the "stop editing if a user clicked on a form" path). Apparently that has a side effect that you *have* to actually press enter to commit your input, otherwise TextEditFinish would not fire and you're going to lose what you've just typed in. Simple repro: open the base screen, write a different name for a base (without hitting enter!), then close the base screen. Reopen the base screen and look at the base name - it's going to be the one before the edit.

For what it's worth, in the Android port of OpenXcom TextEdit was set up in a way that would trigger an equivalent of Text_StartInput (actually just SDL_StartTextInput) each time a user would "click"/tap on the field. That was done because user could accidentally close the virtual keyboard, and the app would not get an event for that, which could lead to getting stuck in some places.

**Comment by pmprog** [comment]
I just grabbed whatever was head about 5 hours ago.
So is the problem that it doesn't start editing, or that it doesn't commit changes when it loses focus?

**Comment by sfalexrog** [comment]
Well, at the time of opening the issue TextEdit just plainly didn't work at all :) But right now it's more of a hack, with commented-out code and missing some of the events. And I'm not even sure how it's *supposed* to work, unfortunately.

**Comment by SupSuper** [comment]
Here's what I know about the TextEdit history:
- Back in the Allegro days, when it was all @pmprog 's code, it all worked fine. You could click on the textedit to focus, move cursor with arrows, input text, press Enter to finalize changes, etc. The base name was never saved though, which I never figured out why. It's probably unrelated though.
- Later @JonnyH changed the event system so everything got events, which broke the TextEdit focus because a click on the TextEdit activated it while a click outside deactivated it, and now both the TextEdit and its parent handled this simultaneously (I think Handled is ignored?? ask @JonnyH)
- Later we moved to SDL2 so I changed the events to standard Input events. I don't know if that broke anything.
Conclusion: ???
