### ISSUE TITLE
Source tree: Check-in auto-generated code

### ISSUE THREAD

**Issue by sfalexrog** [pmprog/OpenApoc#86]
Since 2ac50b1228, some of the source files are auto-generated during build phase. Right now this works just fine for me as long as I'm using cmake && make combo, but some IDEs that claim cmake compatibility (*cough*clion*cough*) choke on the file generation process. What's even more concerning is the possibility of "cross-compiling" for other platforms with, uh, "native" tools. I'm pretty sure it's not *that* complicated to add some gradle magic to android builds and get all the files generated, but that'd actually require some build tools outside of the SDK+NDK combo.

Another point is that we've got some "auto-generated" data in the repo anyway (though it's not a fair comparison, seeing how regenerating data would take considerably longer and it's not compiled in), so generated files *should* not be a big problem, provided we regenerate them once in a while.

**Comment by JonnyH** [comment]
Really, the only reason I haven't made the 'initial gamestate' generation part of the build process is it require the cd.iso to be accessible (and a specific version of the cd at that).
Going forward, I would be strongly against checking-in the generated source, and there are some places (e.g. a game editor, so might not be affecting android) where there may be more generated files.

If there is anything we can do to the cmake to make it more amenable to your build? Use a script instead of a built program? (requiring windows users to install python and get it so msbuild can see it might be difficult, but certainly solve-able)

**Comment by sfalexrog** [comment]
Well, truth be told, it's not a major problem - it's quite easy to just execute an external script from gradle that would build the generator and run it before compiling the project. It would require the builder to have an easily accessible compiler, but Android Studio on Windows was a shitshow the last time I've checked anyway.
As for other platforms - well, there's probably no problem there to begin with, except for those weird "CMake-based" IDEs that override your binary paths (for the record, my game/state/CMakeLists.txt@141 reads `${CMAKE_BINARY_DIR}/tools/gamestate_serialize_gen/OpenApoc_GamestateSerializeGen`), but that's fine.

So yeah, if our policy on generated files is "generate them during build if possible", I'm very much fine by that.

**Comment by JonnyH** [comment]
It's possible I should be using ${CMAKE_BINARY_DIR} anyway, if your change also works on non-android builds feel free to push.
